Repository 2023-Winter-techeer-Bootcamp-Team-E/backend, pull requests merged in 2024-01, with the labels that each got.

#2 chore : 개발 환경 세팅
  haruProject/.gitignore
  haruProject/requirements.txt
Labels: 👩🏻‍💻chore

#4 Chore/#3 기초 개발 환경 세팅 수정
  .github/PULL_REQUSET_TEMPLATE.md
  .gitignore
  .idea/.gitignore
  .idea/backend.iml
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  haruProject/config/__init__.py
  haruProject/config/asgi.py
  haruProject/config/settings.py
  haruProject/config/urls.py
  haruProject/config/wsgi.py
  haruProject/manage.py
  requirements.txt
Labels: 👩🏻‍💻chore

#8 chore: asgi 서버 설정, diary 패키지 생성
  haruProject/config/asgi.py
  haruProject/config/urls.py
  haruProject/diary/routing.py
Labels: 👩🏻‍💻chore

#13 feat: guest 비밀번호 검증 구현 및 조회
  haruProject/config/settings.py
  haruProject/config/urls.py
  haruProject/guest/__init__.py
  haruProject/guest/admin.py
  haruProject/guest/apps.py
  haruProject/guest/models.py
  haruProject/guest/serializers.py
  haruProject/guest/tests.py
  haruProject/guest/urls.py
  haruProject/guest/views.py
Labels: feature

#15 Feat/#11 member 회원가입, 로그인, 로그아웃 구현
  haruProject/config/settings.py
  haruProject/config/urls.py
  haruProject/member/__init__.py
  haruProject/member/admin.py
  haruProject/member/apps.py
  haruProject/member/models.py
  haruProject/member/serializers.py
  haruProject/member/tests.py
  haruProject/member/urls.py
  haruProject/member/views.py
Labels: feature

#16 Feat: Diary 기능 구현
  haruProject/config/settings.py
  haruProject/config/urls.py
  haruProject/diary/__init__.py
  haruProject/diary/admin.py
  haruProject/diary/apps.py
  haruProject/diary/consumers.py
  haruProject/diary/models.py
  haruProject/diary/serializers.py
  haruProject/diary/tests.py
  haruProject/diary/urls.py
  haruProject/diary/views.py
Labels: feature

#18 Feat/#12
  .idea/backend.iml
  .idea/misc.xml
  haruProject/config/settings.py
  haruProject/config/urls.py
  haruProject/diary/models.py
  haruProject/guest/models.py
  haruProject/guest/urls.py
  haruProject/guest/views.py
  haruProject/harucalendar/__init__.py
  haruProject/harucalendar/admin.py
  haruProject/harucalendar/apps.py
  haruProject/harucalendar/models.py
  haruProject/harucalendar/serializer.py
  haruProject/harucalendar/tests.py
  haruProject/harucalendar/urls.py
  haruProject/harucalendar/views.py
  haruProject/member/serializers.py
Labels: feature

#22 Feat/#19
  haruProject/diary/models.py
  haruProject/diary/serializers.py
  haruProject/diary/urls.py
  haruProject/diary/views.py
  haruProject/harucalendar/models.py
  haruProject/harucalendar/serializer.py
  haruProject/harucalendar/views.py
  haruProject/member/models.py
  haruProject/member/serializers.py
Labels: feature

#24 Feat/#14 텍스트 추출 및 이미지 생성 API 구현
  haruProject/config/settings.py
  haruProject/diary/models.py
  haruProject/diary/serializers.py
  haruProject/diary/urls.py
  haruProject/diary/utils.py
  haruProject/diary/views.py
  haruProject/harucalendar/models.py
  requirements.txt
Labels: feature

#29 Refacor: 멤버 기능 정리
  .gitignore
  docker-compose.yml
  haruProject/config/settings.py
  haruProject/config/urls.py
  haruProject/diary/serializers.py
  haruProject/diary/swaggerserializer.py
  haruProject/diary/urls.py
  haruProject/diary/utils.py
  haruProject/diary/views.py
  haruProject/harucalendar/models.py
  haruProject/harucalendar/serializer.py
  haruProject/harucalendar/swaggerserializer.py
  haruProject/harucalendar/urls.py
  haruProject/harucalendar/views.py
Labels: refacor

#28 Feat/#23
  .gitignore
  docker-compose.yml
  haruProject/config/settings.py
  haruProject/config/urls.py
  haruProject/diary/serializers.py
  haruProject/diary/swaggerserializer.py
  haruProject/diary/urls.py
  haruProject/diary/utils.py
  haruProject/diary/views.py
  haruProject/harucalendar/models.py
  haruProject/harucalendar/serializer.py
  haruProject/harucalendar/swaggerserializer.py
  haruProject/harucalendar/urls.py
  haruProject/harucalendar/views.py
Labels: feature

#35 Refacor/#25
  haruProject/diary/swaggerserializer.py
  haruProject/diary/views.py
  haruProject/static/swaggerserializer.py
  haruProject/static/views.py
  requirements.txt
Labels: refactor

#36 refacor: calendar에 calendar_id 세션 추가
  haruProject/harucalendar/views.py
Labels: refactor

#47 fix: swagger 무한로딩 버그 수정
  haruProject/config/settings.py
  haruProject/config/urls.py
  haruProject/diary/swaggerserializer.py
  haruProject/diary/urls.py
  haruProject/diary/views.py
  haruProject/harucalendar/views.py
Labels: bug

#53 [feat] diary, claendar api,swagger 수정
  haruProject/diary/models.py
  haruProject/diary/serializers.py
  haruProject/diary/swaggerserializer.py
  haruProject/diary/urls.py
  haruProject/diary/views.py
  haruProject/harucalendar/models.py
  haruProject/harucalendar/serializer.py
  haruProject/harucalendar/swaggerserializer.py
  haruProject/harucalendar/urls.py
  haruProject/harucalendar/views.py
Labels: feature

#57 docker-compose에서 celery 관련 오류 수정 및 celery 비동기 처리 구현.
  docker-compose.yml
  haruProject/config/__init__.py
  haruProject/config/celery.py
  haruProject/config/settings.py
  haruProject/diary/tasks.py
  haruProject/diary/utils.py
  haruProject/diary/views.py
Labels: bug, feature

#62 Fix: develop 버전복구
  .dockerignore
  docker-compose.yml
  haruProject/config/settings.py
  haruProject/config/urls.py
  haruProject/diary/__init__.py
  haruProject/diary/models.py
  haruProject/diary/serializers.py
  haruProject/diary/swaggerserializer.py
  haruProject/diary/urls.py
  haruProject/diary/views.py
  haruProject/diaryRoom/__init__.py
  haruProject/diaryRoom/admin.py
  haruProject/diaryRoom/apps.py
  haruProject/diaryRoom/models.py
  haruProject/diaryRoom/templates/chat/room.html
  haruProject/diaryRoom/tests.py
  haruProject/diaryRoom/urls.py
  haruProject/diaryRoom/views.py
  haruProject/haruRoom/admin.py
  haruProject/harucalendar/swaggerserializer.py
  haruProject/harucalendar/urls.py
  haruProject/harucalendar/views.py
Labels: bug

#70 [Refactor] calendar, diary api,swagger 수정
  haruProject/diary/swaggerserializer.py
  haruProject/diary/urls.py
  haruProject/diary/views.py
  haruProject/harucalendar/swaggerserializer.py
  haruProject/harucalendar/views.py
Labels: refactor

#74 Refactor : 키워드 예외 처리
  .dockerignore
  docker-compose.yml
  haruProject/config/settings.py
  haruProject/diary/tasks.py
  haruProject/diary/utils.py
  haruProject/diary/views.py
Labels: bug, refactor

#78 fix : 일기 조회 오류 수정 및 post diary 생성 API 반환값 수정
  haruProject/diary/views.py
Labels: bug

#79 refactor : is_expiry 중복 제거
  haruProject/harucalendar/views.py
Labels: refactor

#83 [fix] member.views.py SignUpView 클래스 수정
  haruProject/member/serializers.py
  haruProject/member/views.py
Labels: bug

#84 Feat#/72
  haruProject/diary/swaggerserializer.py
  haruProject/diary/urls.py
  haruProject/diary/views.py
  haruProject/harucalendar/serializer.py
  haruProject/harucalendar/views.py
Labels: feature

#88 refactor : 작성중인 diary 일기 조회 API 수정
  haruProject/diary/serializers.py
  haruProject/diary/swaggerserializer.py
  haruProject/diary/tasks.py
  haruProject/diary/urls.py
  haruProject/diary/views.py
Labels: refactor

#90 refactor : diary API response data 수정
  haruProject/diary/views.py
Labels: refactor

#91 feat : 일기 생성 시 배경지 로직 구현
  haruProject/diary/models.py
  haruProject/diary/serializers.py
  haruProject/diary/swaggerserializer.py
  haruProject/diary/views.py
  haruProject/static/models.py
Labels: feature, refactor

#98 login method 수정
  haruProject/config/settings.py
  haruProject/diary/tasks.py
  haruProject/diary/utils.py
  haruProject/diary/views.py
  haruProject/member/views.py
Labels: refactor

#100 Feat/#86 모니터링 연동 및 grafana 자동 연동 추가
  docker-compose.yml
  grafana/provisioning/dashboards/dashboard.yml
  grafana/provisioning/dashboards/django_dashboard/9528_rev1.json
  grafana/provisioning/dashboards/telegraf_dashboard/14900_rev2.json
  grafana/provisioning/datasources/datasource.yml
  haruProject/config/settings.py
  haruProject/config/urls.py
  nginx/nginx.conf
  prometheus/prometheus.yml
  requirements.txt
  telegraf.conf
Labels: feature

#103 [refactor]프롬프트 수정
  haruProject/diary/tasks.py
  haruProject/diary/utils.py
Labels: refactor

#104 feat : AWS 로드밸런서로 https 적용 완료
  docker-compose.yml
  haruProject/config/settings.py
  haruProject/diary/tasks.py
Labels: feature, refactor

#107 diary put method 수정
  haruProject/config/settings.py
  haruProject/diary/serializers.py
  haruProject/diary/swaggerserializer.py
  haruProject/diary/views.py
  haruProject/harucalendar/serializer.py
  haruProject/harucalendar/views.py
Labels: refactor

#110 [refactor] diary post method 수정
  haruProject/config/settings.py
  haruProject/diary/views.py
Labels: refactor

#112 [Feat] 백엔드 로그 추가
  docker-compose.yml
  haruProject/config/settings.py
  haruProject/diary/views.py
  haruProject/harucalendar/views.py
  haruProject/member/views.py
  haruProject/static/views.py
  nginx/nginx.conf
Labels: feature

#114 feat : RDS DB 설정 (현재는 주석처리)
  haruProject/config/settings.py
Labels: 👩🏻‍💻chore

#116 [Refactor] celery 동시성 문제 해결
  Dockerfile
  docker-compose.yml
  haruProject/config/celery.py
  haruProject/config/wsgi.py
  haruProject/diary/tasks.py
  haruProject/diary/utils.py
  haruProject/diary/views.py
  haruProject/harucalendar/views.py
  haruProject/member/views.py
  requirements.txt
Labels: refactor

#119 Feat/#92 websocket 기능구현
  haruProject/config/asgi.py
  haruProject/config/settings.py
  haruProject/config/urls.py
  haruProject/diary/consumers.py
  haruProject/diary/models.py
  haruProject/diary/routing.py
  haruProject/diary/serializers.py
  haruProject/diary/swaggerserializer.py
  haruProject/diary/templates/room.html
  haruProject/diary/urls.py
  haruProject/diary/utils.py
  haruProject/diary/views.py
  haruProject/guest/views.py
  haruProject/harucalendar/serializer.py
  haruProject/harucalendar/swaggerserializer.py
  haruProject/harucalendar/views.py
  haruProject/member/views.py
  haruProject/static/views.py
Labels: bug, feature, 👩🏻‍💻chore, refactor

#122 diary is_expiry 기능 추가
  haruProject/diary/views.py
Labels: feature

#123 Refactor/#118 elk 폴더 추가 및 모니터링 수정, docker-compose 분리
  docker-compose.elk.yml
  docker-compose.monitoring.yml
  docker-compose.yml
  elk/.gitattributes
  elk/LICENSE
  elk/elasticsearch/.dockerignore
  elk/elasticsearch/Dockerfile
  elk/elasticsearch/config/elasticsearch.yml
  elk/filebeat/.dockerignore
  elk/filebeat/Dockerfile
  elk/filebeat/config/filebeat.yml
  elk/kibana/.dockerignore
  elk/kibana/Dockerfile
  elk/kibana/config/kibana.yml
  elk/logstash/.dockerignore
  elk/logstash/Dockerfile
  elk/logstash/config/logstash.yml
  elk/logstash/pipeline/logstash.conf
  elk/setup/.dockerignore
  elk/setup/Dockerfile
  elk/setup/entrypoint.sh
  elk/setup/lib.sh
  elk/setup/roles/filebeat_writer.json
  elk/setup/roles/heartbeat_writer.json
  elk/setup/roles/logstash_writer.json
  elk/setup/roles/metricbeat_writer.json
  grafana/provisioning/dashboards/django_dashboard/9528_rev1.json
  grafana/provisioning/dashboards/telegraf_dashboard/14900_rev2.json
  monitoring/grafana/provisioning/dashboards/cadvisor_dashboard/14900_rev2.json
  monitoring/grafana/provisioning/dashboards/dashboard.yml
  monitoring/grafana/provisioning/dashboards/node_exporter_dashboard/9528_rev1.json
  monitoring/grafana/provisioning/datasources/datasource.yml
  monitoring/prometheus/prometheus.yml
  nginx/nginx.conf
  prometheus/prometheus.yml
  telegraf.conf
Labels: refactor

#132 refactor: 모니터링 수정 진짜 완료
  docker-compose.monitoring.yml
  haruProject/config/settings.py
  monitoring/grafana/provisioning/dashboards/Docker_and_system_monitoring_dashboard/14900_rev2.json
  monitoring/grafana/provisioning/dashboards/cadvisor_exporter_dashboard/cadvisor_exporter.json
  monitoring/grafana/provisioning/dashboards/dashboard.yml
  monitoring/grafana/provisioning/dashboards/django_dashboard/django_dashboard.json
  monitoring/grafana/provisioning/dashboards/node_exporter_dashboard/9528_rev1.json
  monitoring/prometheus/prometheus.yml
Labels: refactor

#136 refactor: diaries view 수정
  haruProject/diary/swaggerserializer.py
  haruProject/diary/views.py
Labels: refactor

#139 backend log ELK stack 연동
  haruProject/config/settings.py
  haruProject/diary/views.py
Labels: feature
